### ISSUE TITLE
Elevated privileges – Jesse

### ISSUE THREAD

**Issue by jessekozler** [dchan-lab/dchanlab#153]
In this issue I will track the process of requesting elevated privileges for the lab's private server as the designated manager for the first year RA cohort. I will follow the process laid out in this [wiki page](https://github.com/dchan-lab/dchanlab/wiki/Requesting-Elevated-Privileges).

**Comment by jessekozler** [comment]
@chand04 I want to share the steps I've taken on all three of the items in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1625775431 as of EOD yesterday. 

1. I had IT route a duplicate incident ticket to the Systems Management group and we'll see what they have to say in response. I am still looking for the channel through which to contact Domain Infrastructure; the IT help desk was unable to provide contact information for that group.
2. I tried to call the Palo Alto OIT office but their phone extension just routes to the general IT help desk line. I'll try to hunt around on Teams for the person I talked to in January. 
3. I emailed the IT agent on Friday as requested, and through Vault/CABAL he was able to see you and someone named Kenneth Fuchsel listed as POCs. I've reached out to Kenneth on Teams with the error screenshot and asked whether he has any insight into what's going on.

I'll post more updates once I receive responses.

**Comment by chand04** [comment]
Thanks, @jessekozler, for pinging people more actively. Do you have any reflections on how your experience differed from Saam's?

**Comment by jessekozler** [comment]
@chand04 I have good news, Kenneth responded to my Teams message and instructed me to send the same query to the VINCI SA Team (VINCISATeam@va.gov). I would guess SA stands for Server Administration or something to that effect, but there is nothing referencing this in the wiki. This email address comprises 44 IT professionals, one of whom happens to be the one and only Victor Lekhakul. He responded within the hour with "I got this one" on behalf of the team, and within the next hour resolved the issue, with the following explanation:

>Your NMEA/ePAS request is only for access to the server. VINCI also has a separate "gateway" server that manages ALL users accessing our environment and your NMEA account was not a member. I've just added your NMEA account to the group so you should be able to access Dev301 now.

Indeed, once he added my account to the group, I was able to log on. In my response, I thanked him profusely, and also asked whether future lab members can do anything else to ensure membership in this group, i.e., whether one can fill out a companion ePAS form for `vhacdwdwhrdgat.vha.med.va.gov`, or whether they should just ping him on Teams to get added.

To your question about my process vs. Saam's, this was something I spoke with him about when we audited my ePAS form in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1593503136, and I've additionally read through the comment thread in https://github.com/dchan-lab/dchanlab/issues/122. Here are my takeaways:
- Saam's process at least initially involved an OTP token in addition to the USB token whereas mine didn't, and the USB tokens are possibly being phased out as well per https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1560187352. So, at a high level, it seems like the VA's policies on elevated privileges have been in flux in recent years, and we should be aware that they may continue to change for future RAs. 
- In #122 Saam mentions the USB token not working on his Macbook and Strong Authentication's warning that they often don't play nicely with Macs; I just want to note for future RAs that I have had the same experience of only ever being able to use it on the machine we have in the office, or one at Palo Alto OIT. 
- Saam mentions in https://github.com/dchan-lab/dchanlab/issues/122#issuecomment-1134983652 that he worked with Victor on this elevated privileges issue. In conversation, he indicated that Victor had been instrumental in the process and set up a lot of it on his end; it seems to me very likely that the RD gateway clearance was one of those items that Victor took care of. In https://github.com/dchan-lab/dchanlab/issues/99, Matthew also mentions liaising with Victor. Neither of these issues mention the specific items he aided with as part of this process, so I am only able to speculate. There is nothing in any past elevated privileges issue, nor the [Requesting Elevated Privileges](https://github.com/dchan-lab/dchanlab/wiki/Requesting-Elevated-Privileges) instructions, nor the rest of the wiki that makes any mention of this RD gateway server group.

The one remaining confusion I have is why I was able to log onto our workspace successfully with the admin credentials on the Palo Alto OIT machine but not ours in the office. I suspect there may be some sort of different gateway protocol when using machines within VA facilities that are already hooked up directly to the VA intranet, but I have no clue about how this stuff works on a technical level. 

I got the sense today that you have some concerns over how long this whole process took. If you would like me to audit the six or seven IT tickets that were opened in relation to this issue, plus the various email chains and Teams conversations with members of different IT verticals, and construct a comprehensive timeline like I did in https://github.com/dchan-lab/dchanlab/issues/178#issuecomment-1546043581, please let me know.

Otherwise, I think there are two to-do items from here:
- Update the [Requesting Elevated Privileges](https://github.com/dchan-lab/dchanlab/wiki/Requesting-Elevated-Privileges) wiki page to include mention of this gateway server, as well as any tasks that Victor says future admins need to do.
- Update our [Administrative Contacts](https://github.com/dchan-lab/dchanlab/wiki/Resources,-Codebooks,-and-Contacts#administrative-contacts) wiki section to mention the VINCI SA Team, and Victor specifically, as potential contacts for troubleshooting NMEA clearances.

Once Victor responds and I update the wiki, I will close this issue.

**Comment by chand04** [comment]
@jessekozler, thanks for this update. This is definitely good news, and I'm glad you finally contacted Victor and got this resolved. 

I think an audit and some reflection would be in order. I'm not sure if a super thorough audit is required, but a high-level sense of major chunks of time/effort that could have been saved would be useful. It might also be useful to ask Victor what he thinks you should have done differently to save the most time. To clarify, did this issue only exist in May (in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1560187352), or did it probably exist before May but was just uncovered in May?

**Comment by jessekozler** [comment]
@chand04 on reflection, I think the obvious misstep on my part was not contacting Victor sooner. We know from past experience, most recently https://github.com/dchan-lab/dchanlab/issues/178, that he is a prompt and helpful, especially on issues related to server administration. I have been wary about bothering him too much, but that isn't an excuse to have not reached out to the right resource. In hindsight, the numerous calls to the IT help desk feel a little bit like that apocryphal quote about insanity as doing the same thing over and over and expecting different results...

> To clarify, did this issue only exist in May (in [#153 (comment)](https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1560187352)), or did it probably exist before May but was just uncovered in May?

My understanding is this issue existed before I discovered it in May.

From Victor today re: future RAs needing this access in the future:

> Anything related to VINCI and your server, please send an email to vinci@va.gov. Normally when you open up a ticket in SNOW, it _should_ come to us if you put down the server name. That's why we use direct email request, we've seen tickets get lost for a bit before it gets to us.
>
> NMEA is just like any new user, just with a bit more restriction. As with any new user, you still have to submit a request for VINCI access. 

Are you ok with me adding some of this contact info to the wiki then closing this issue?

**Comment by chand04** [comment]
@jessekozler, thanks. Contacting Victor sounds like a good assessment of how we could have reduced the time and headache. As you say in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1593503136, Saam liaised with Victor. 

I'm unsure if I understand Victor's email. Can you please parse it for me? Did you open a SNOW ticket rather than send an email to vinci@va.gov? Did Saam submit a request for VINCI access, while you did not? Please provide a summary of changes to the wiki you propose.

**Comment by jessekozler** [comment]
@chand04 of course, no problem.

> Did you open a SNOW ticket rather than send an email to [vinci@va.gov](mailto:vinci@va.gov)?

By SNOW (i.e., ServiceNow?) tickets I believe he's referring to the Incident Tickets in the yourIT Service Portal; these are created by the IT enterprise service desk whenever you call them. So yes, several of these were created for me. I didn't email vinci@va.gov—I actually see that email included in [this](https://github.com/dchan-lab/dchanlab/wiki/Accessing-VA-Data#va-informatics-and-computing-infrastructure-vinci) wiki page, in fact explicitly relating to "you do not have appropriate permissions to access" error messages. So, a closer look through the wiki, and searching key terms in the error message, would definitely have gotten me to the right point contact sooner as well... 

> Did Saam submit a request for VINCI access, while you did not?

There was not a separate, secondary submission in his ePAS document history when we looked, no. We submitted the same document. 

> Please provide a summary of changes to the wiki you propose.

For right now, I would add the following bullets to [this](https://github.com/dchan-lab/dchanlab/wiki/Resources,-Codebooks,-and-Contacts#data-and-software-contacts) section, comprising Victor's recommendation:

```
- Server access issues (including with NMEA)
  - Email vinci@va.gov and include the name of the server in question (vhacdwdwhdev301.vha.med.va.gov) in the subject line
```

Conservatively, I'm not sure if anything else needs to be added at this point, but when one of the new RAs does this process in the next few months, I'll make sure to solicit feedback on how they find the wiki. Based on that (and seeing whether they run into this problem) we can propose additional tweaks as needed.

**Comment by chand04** [comment]
@jessekozler, sorry, I'm still confused why Victor said this to you:

> NMEA is just like any new user, just with a bit more restriction. As with any new user, you still have to submit a request for VINCI access.

As server manager, what capabilities do you have? I.e., if someone else has server access issues, can you help them with it?

**Comment by jessekozler** [comment]
@chand04 these are good questions, I'll follow up with Victor and request clarification on whether "submit[ting] a request for VINCI access" constitutes a separate ePAS document or just an email to vinci@va.gov. I'll also ask whether I can add others to this RD gateway group or otherwise help with troubleshooting access issues.

**Comment by chand04** [comment]
Hi Jesse,

Thanks. As some feedback: I wanted to highlight that the first part of my
post was to ask what Victor meant, and I would hope that you would fully
digest what he’s saying before passing it along to me.

Best,
Dave

**Comment by jessekozler** [comment]
@chand04 thanks for the feedback. I read `As with any new user, you still have to submit a request for VINCI access.` as just reiterating the prior bit about needing to contact vinci@va.gov to get the NMEA account added as a member to the access groups. I agree though that I should have cleared up any ambiguity with Victor before looping you in, especially because these IT procedures demand a high degree of precision in execution from past experience.

**Comment by chand04** [comment]
@jessekozler, thanks. Sorry, reading the wiki [here](https://github.com/dchan-lab/dchanlab/wiki/Requesting-Elevated-Privileges), I see this:

> After your token is activated and your NMEA is working (you may want to double check this if you're working on a Mac), you'll have to email the VINCI coordinator asking for your NMEA (your _0 account) to be added to the private server (again VHACDWDWHDEV301.VHA.MED.VA.GOV) and the remote desktop server (VHACDWDWHRDGAT.VHA.MED.VA.GOV). After this is done, you should be able to login to our private server using your NMEA (necessary in order to install/remove software).

Is this saying the same thing that Victor is saying? (Or did you do that before May?)

**Comment by chand04** [comment]
@jessekozler, following up on this issue.

**Comment by jessekozler** [comment]
@chand04, thanks for your patience while this issue took a back seat the past couple days.

Following up on https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1636279084, there is no separate ePAS document, admins just need to email the VINCI team, and I am not able to add people to the RD gateway permissions group.

> Is this saying the same thing that Victor is saying? (Or did you do that before May?)

Yes, this is the same thing Victor is talking about (i.e., RD gateway := remote desktop server). As far as step (4) in the wiki, I did when I originally got access back in January but not after the second time I submitted the ePAS document in June. 

In rereading the wiki, I also saw this line:

> You will need to respond to a quarterly email to confirm that you still need the elevated privileges.

I did not respond to this email, and in fact don't remember receiving it, so I fear I deleted it by accident. Since last week I've reached out to VINCI to confirm this would have been responsible for my NMEA account's group memberships being revoked, hence the login error. (As a note for future admins, they also told me that email comes from the ESD support team specifically.) Aside from that, your bringing up that page in conjunction with Victor's note made me realize that I could have arrived at a solution sooner by more carefully searching/reading the wiki, as that same `vhacdwdwhrdgat.vha.med.va.gov` server name was cited in the details of the error message. 

So, to summarize, I made several unforced errors in this process:
- Quarterly confirmation email miss: I was not adequately attentive to my inbox, nor did I keep details from the wiki closely enough in mind.
- Incomplete re-attempt of the ePAS process: I did not finish step (4) after Saam and I audited the ePAs document in June (nor did I re-do step (1), although I don't think that is material). This would have cleared up the error. 
- Sub-optimal outreach strategy: rather than reaching out to Victor as a first line of defense on server issues, I repeatedly phoned the IT help desk.
- Sub-optimal detective work: by searching key terms in the details of the error message, I would have been able to piece together the solution more quickly and directly.

I think the common thread in all of these errors was a lack of attention to detail vis-à-vis the wiki. I stand by my proposed addition in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1635217899 as useful, but the wiki was not at fault here and I do not think it requires further revision. 

Please do let me know if you have any other thoughts on this in closing, and I'm sorry this was a bit of a debacle.

**Comment by chand04** [comment]
@jessekozler, thanks so much for the thoughtful reflection. This highlights the importance of checking the wiki. 

For the proposed wiki addition in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1635217899, shouldn't the lab administrator(s) be the first contact for access to the development server? The second contact would then be vinci@va.gov.

**Comment by jessekozler** [comment]
@chand04 great point, here is my proposed addition to the Data and Software Contacts [section](https://github.com/dchan-lab/dchanlab/wiki/Resources,-Codebooks,-and-Contacts#data-and-software-contacts) of the Resources, Codebooks, and Contacts wiki:

> - Server access issues (including with NMEA)
>     - Talk to the lab's server administrator(s) first, they may be able to help and should be made aware of any such issues in the lab regardless 
>     - Email vinci@va.gov and include the name of the server in question in the subject line

**Comment by chand04** [comment]
@jessekozler, two questions:
- Does NMEA apply to lab members outside of the lab server administer? I don't think most people will know what NMEA is. If NMEA only applies to the lab server administrator, then it should only belong on the wiki page for those applying to be a lab server administrator.
- What types of server access issues are there? Are there only server access issues for our private server? Or are there other VINCI server access issues?

**Comment by jessekozler** [comment]
@chand04 all good questions, happy to clarify:

> * Does NMEA apply to lab members outside of the lab server administer? I don't think most people will know what NMEA is. If NMEA only applies to the lab server administrator, then it should only belong on the wiki page for those applying to be a lab server administrator.

NMEA (Non Mail Enabled Accounts) are the separate accounts with `0` suffixes that we apply for through the ePAS documents; the server admins are the only ones with those. I agree in order to avoid confusion we could change it to "including with server admin accounts." I would suggest leaving this here though, as server access issues are not limited to server admins. For example in https://github.com/dchan-lab/dchanlab/issues/182#issuecomment-1636346033, Melinda had one of these remote desktop gateway errors pop up. She did both steps in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1646214893 and they were able to correct things promptly. 

> * What types of server access issues are there? Are there only server access issues for our private server? Or are there other VINCI server access issues?

No, server access issues are not limited to our private Development Workspace. The aforementioned error Melinda had was restricted to the Standard Workspace. As far as other possible types of VINCI server access issues, I'm admittedly not sure, but I intentionally left the wording of this a bit broad in the hopes of encouraging the use of the VINCI team as the primary contact for anything falling under that umbrella (that is, maybe it would nudge someone away from repeating my mistake of going through the general IT help desk). 

Please let me know if you agree with that reasoning!

**Comment by chand04** [comment]
@jessekozler, thanks. Maybe you can clarify what the lab server administrator would be able to help with. I know that accessing the development workspace is one such issue. What other issues can the lab server administrator help with? 

Outside of these issues, I'm not sure if this is helpful: "Talk to the lab's server administrator(s) first, they may be able to help and should be made aware of any such issues in the lab regardless." For making others "aware" of issues, we usually use the listserv anyway.

**Comment by jessekozler** [comment]
> Maybe you can clarify what the lab server administrator would be able to help with. I know that accessing the development workspace is one such issue. What other issues can the lab server administrator help with?

@chand04 to be honest, that's really the only thing I'm aware of server admins being able to help with, access-wise.

> Outside of these issues, I'm not sure if this is helpful: "Talk to the lab's server administrator(s) first, they may be able to help and should be made aware of any such issues in the lab regardless." For making others "aware" of issues, we usually use the listserv anyway.

Yeah, that's a good point, one option would be to remove the first bullet point and revert to the version in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1635217899 with the NMEA wording changed. Another option would be to change to something like:

> - Server access issues 
>    - If it is your first time accessing the Development Workspace, notify the labs server admin(s) and make sure you've been added as a remote desktop user
>   - Otherwise, email [vinci@va.gov](mailto:vinci@va.gov) and include the name of the server in question in the subject line (this applies to server admin accounts as well)

**Comment by chand04** [comment]
@jessekozler, thanks. I noticed that we already have this [here](Server access and program support) on the same wiki page. (I modified it slightly.)

I also noticed that we have the responsibilities for the server admin [here](https://github.com/dchan-lab/dchanlab/wiki/Administrative-Tasks#administering-the-private-server). There, the server admin should make sure to add new users. It should be the responsibility of the server admin to add new users, rather than the responsibility of new users to notify the server admin to add them as remote desktop users.

One other question: Do we really need VINCI to add the server admins with special privileges to the development workspace, or can another server admin do this?

**Comment by jessekozler** [comment]
> I noticed that we already have this [here](https://github.com/dchan-lab/dchanlab/wiki/Resources,-Codebooks,-and-Contacts#:~:text=Server%20access%20and%20program%20support) on the same wiki page. (I modified it slightly.)

@chand04 this looks great, the only thing I would change is replace "standard workspace" to "standard or development workspaces" as the VINCI team can and does assist with both. I think that would suffice as far as wiki content related to this issue is concerned.

> I also noticed that we have the responsibilities for the server admin [here](https://github.com/dchan-lab/dchanlab/wiki/Administrative-Tasks#administering-the-private-server). There, the server admin should make sure to add new users. It should be the responsibility of the server admin to add new users, rather than the responsibility of new users to notify the server admin to add them as remote desktop users.

Yes, that instruction on the wiki page was definitely helpful in https://github.com/dchan-lab/dchanlab/issues/182#issuecomment-1639048715, and I agree that we want to avoid wording which puts the onus on new hires rather than the server admin.

> Do we really need VINCI to add the server admins with special privileges to the development workspace, or can another server admin do this?

Unfortunately, no, server admins cannot do this. That remote desktop gateway group is VA-wide and administered by VINCI, and is separate from giving lab user accounts access to the Dev Workspace from inside the machine as a server admin.

**Comment by chand04** [comment]
Got it, thanks. I think we're good to close this issue!

**Comment by jessekozler** [comment]
### Summary

In this issue, we tracked my application for elevated privileges to be one of our lab's server administrators. The initial process concluded in January, and resulted in a helpful wiki addition, described in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1385758364. In May, a previously-unseen error message popped up, preventing me from accessing the development workspace through my admin account, described in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1560187352. There was a lengthy and, in hindsight, unneeded back-and-forth with IT that followed the discovery of this error. See https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1633333864 for Victor's solution, and a comparison of my process to Saam's. See also https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1645094088 for some lessons learned from this.
