### ISSUE TITLE
Make additions to onboarding presentations

### ISSUE THREAD

**Issue by sambock27** [dchan-lab/dchanlab#163]
In this issue, we will track the progress of updating onboarding presentations for next year. The agenda can be found in https://github.com/dchan-lab/dchanlab/issues/127#issuecomment-1249957664. Below is a checklist from that agenda for actionable items.

**VA Presentation**
- [x] High level diagram of how Github, local machine, VA first layer, VINCI standard workspace, and dev server all relate. 
- [x] GIFs or a video demonstrating a login
- [x] Make explicit that new predocs should login alongside the presentation

**GitHub Presentation**
- [x] Emphasize some best practices that go overlooked e.g. posted results should be accompanied by a commit

**Week in the Life Presentation**
- [x] Explain the kinds of issues (literature review, exploratory, data pull, final analysis, production) that we may work on

**Wiki**
- [x] Some references may be out of date — for example, Microsoft SQL Server 2016
- [x] Add a section explaining frequently used markdown commands — multiline code, bullets, headers, dropdowns, comment links

**Other**
- [x] Explanation on how to gain access to operations data
- [x] Explanation on how to access SAS on remote desktop (maybe this can be a wiki or video explanation)

**Comment by chand04** [comment]
@sambock27 @jessekozler @jtprates @kemin98, sorry for realizing this late, but I just noticed that we don't discuss a few things that new RAs may have questions about: ClickUp, Monday check-ins, and lab meetings. Should someone discuss those in greater detail in a presentation?

**Comment by sambock27** [comment]
Hi @chand04, I think [we agreed](https://docs.google.com/document/d/1KzpAI-oShNny-lpZEfQFkY6CRom2ns_fv9RiZWfdxhM/edit) to do a "mock lab check-in" as a part of the "Week in the Life" presentation on Wednesday. We also discuss lab meetings during the Week in the Life presentation, but I will be sure to give it special attention while presenting.

**Comment by sambock27** [comment]
@chand04 can I close this issue back up? Or should I keep it open as a channel to discuss onboarding this week?

**Comment by chand04** [comment]
Thanks for asking, @sambock27! Yes, let's close it, and I'll do that now.
