### ISSUE TITLE
Tracking WOC Process - Melinda

### ISSUE THREAD

**Issue by jtprates** [dchan-lab/dchanlab#172]
We will use this issue to track @melinda-xu 's WOC application process. A few helpful examples of this from last year are #123, #125, and #126, and you can also find helpful guidance in this [wiki page](https://github.com/dchan-lab/dchanlab/wiki/WOC-Appointment-Guidance).

Let me know if you have any questions :)

**Comment by melinda-xu** [comment]
### SUMMARY ###
In this issue, we have tracked my WOC process at VA Palo Alto.

#### Timeline

|Date|Event|
|-----|-------|
|3/27/2023|Accessed RDIS. Completed training and WOC Appointment forms|
|4/3/2023|Mailed out forms to Linda|
|5/4/2023|Mailed forms were lost. Emailed forms. Receipt of forms confirmed by Linda.|
|5/9/2023|Received and completed Federal Background Investigation|
|5/12/2023|Received and signed WOC appointment letter|
|5/18/2023|Completed Fingerprinting|
|6/27/2023|Background check completed and favorable determination made|
|6/30/2023||Receipt of email saying WOC Appointment was completed. Assigned VA Email and PIV card ready to be picked up|
|7/05/2023|PIV appointment made through Jo. PIV had IT migration issues and was unable to pick up card|
|7/12/2023|IT issues fixed. Picked up PIV card.|

#### Areas for improvement

1. I waited a long time figuring out what happened to the forms I mailed to Linda. She never received them and they ended up being lost. I recommend to future RAs to try to email the forms before mailing, as that worked immediately for me.
2. My PIV card had migration issues, an error we've never experienced before. I don't think that there is anything to do to prevent this, but keep in mind that this may happen in the future.
