### ISSUE TITLE
Track WOC renewal  - Jo

### ISSUE THREAD

**Issue by jtprates** [dchan-lab/dchanlab#177]
We will use this issue to track the renewal of my WOC appointment and my new PIV badge. The purpose of this issue is to establish a timeline and steps of the renewal process, to help future lab members that have to go through it.

**Comment by chand04** [comment]
@jtprates, thanks, and great to hear. Let's make sure to include some reflections on how we could have sped up the process.

**Comment by jtprates** [comment]
### SUMMARY ###

In this issue, we have tracked my WOC appointment renewal. A timeline and reflections regarding the process are given below:

#### Timeline

|Date|Event|
|-----|-------|
|3/19|Filled out STEM OPT extension application|
|4/19|Extension Granted by USCIS|
|4/28|New EAD card received|
|5/1| Sent all required documents to Linda Wester. New WOC appointment letter received and processed |
|5/19| WOC appointment processed; PIV pick-up scheduled | 
|7/7| PIV appointment at the VA. Badge began printing in DC | 
|7/12| PIV badge picked up | 

#### Reflections regarding the process
- Filling out the STEM OPT extension form (I-765) is pretty straightforward, but the training plan (I-983) may require some more work. RAs have to fill out the training plan portion, which is quite long. My training plan section attached here may be helpful :  [i983_plan.pdf](https://github.com/dchan-lab/dchanlab/files/11368060/i983_plan.pdf)
- Sponsors (i.e., Linda), can set two different options for printing a badge: centrally in DC, or locally where the PIV appointment was at. My badge was set to central printing, and this meant having to wait 5 more days to actually pick it up. We should make sure with Linda that our PIVs are set to local printing before heading to our PIV appointments.
- Through the course of this issue, we found out that PIV appointments can scheduled at any VA facility. This can speed up the PIV process in two ways:
    1. RAs in the bay area can set an appointment in SF if Palo Alto does not have available appointments;
    2. RAs that are elsewhere in the United States when their WOC is approved can schedule an appointment where they are (instead of having to wait to come to Palo Alto to do it)

- While the Palo Alto VA does not always have appointments readily available, they do take walk-ins, and this can speed things up. Call beforehand for availability, using the number in [this page](https://www.osp.va.gov/Badge_Office_Locations.asp) (link already in WOC the wiki).
