### ISSUE TITLE
Onboarding exercises - Melinda

### ISSUE THREAD

**Issue by sambock27** [dchan-lab/dchanlab#182]
In this issue, we will track the progress of @melinda-xu's onboarding exercises. Below is a list of tasks in a suggested order.

- [x] Read [lab wiki](https://github.com/dchan-lab/dchanlab/wiki) (throughout week)
- [x] [w3 SQL tutorial](https://www.w3schools.com/sql/default.asp)
- [x] [SQL exercise](https://m-soro.github.io/Business-Analytics/SQL-for-Data-Analysis/L4-Project-Query-Music-Store/)
- [x] [GitHub onboarding task](https://github.com/dchan-lab/practice/wiki/GitHub-Onboarding-Task) (after Tuesday)
- [x] [VA orientation task](https://github.com/dchan-lab/practice/wiki/VA-Orientation-Task)
- [x] SQL PR task (let me know when you are ready. You should read the wiki and complete the w3 SQL tutorial before this)
- [x] [VA data SQL task](https://github.com/dchan-lab/practice/wiki/VA-Data-SQL-Task)
- [x] [Debugging task](https://github.com/dchan-lab/dchanlab/wiki/Debugging-task-instructions)

We are having trouble accessing some of the instructions for these items through GitHub at the moment, but the first few items are available and should give you enough to do for the first couple of days.

**Comment by sambock27** [comment]
Hi @melinda-xu, I hope the meeting today was a helpful window into how our lab operates. I understand that not everything might have instantly sunk in, so I wanted to point you in the direction of the presentations from today. Our presentation on general VA infrastructure can be found [here](https://github.com/dchan-lab/dchanlab/blob/master/presentations/orientation/2023/Intro_to_VA.pdf), and you can find the presentation on VINCI and GitHub workflow [here](https://github.com/dchan-lab/dchanlab/blob/master/presentations/orientation/2023/GitHub%20%26%20VINCI/GitHub%26VINCI.pdf). 

In addition to these presentations, we have a [video guide](https://github.com/dchan-lab/dchanlab/blob/master/presentations/orientation/2023/login%20video.mp4) for accessing VINCI (this corresponds to the "VA orientation task" in your checklist, but the task has some additional setup steps). We also have a [visual summary](https://github.com/dchan-lab/dchanlab/blob/master/presentations/orientation/2023/VA%20Workflow.pdf) of how VINCI and GitHub relate.

**Comment by jessekozler** [comment]
@chand04 interestingly, @melinda-xu just got an error message very similar to the one I posted in https://github.com/dchan-lab/dchanlab/issues/153#issuecomment-1560187352 when trying to log onto the Standard Workspace:

<details>
<summary> Error message </summary>
<br>

![image](https://github.com/dchan-lab/dchanlab/assets/93345931/49ad6c8c-874f-4de6-b28c-bbf6149f13d0)

</details>

I've instructed her to email vinci@va.gov (per Victor's instructions) and ask them to verify that her user account is added to the Development Workspace, Standard Workspace, and RD Gateway groups to ensure access. 

@kemin98 @jtprates can you both confirm whether you received this type of error last year during onboarding? @sambock27 and I don't recall this issue popping up.

**Comment by jtprates** [comment]
@jessekozler, @chand04 , @melinda-xu, I don't recall receiving this for the Standard workspace in specific. I remember not being able to log onto the Development workspace, and for that I believe I had to be added by an admin to the Dev Workspace.

One thing I can suggest would be to check whether Melinda has remote access privileges, but I'm not sure if this error would be related to that.

**Comment by chand04** [comment]
Thanks, all. I believe that Melinda wouldn't be able to log in to the first layer without remote access. It may be that if she is not on any DART project, then VINCI won't let her log in to the second layer. Let's definitely add her to the lab's DART forms. Asking VINCI also sounds like a good idea.

**Comment by kemin98** [comment]
@chand04 I will add Melinda to all our projects on DART.

**Comment by melinda-xu** [comment]
@jessekozler, VINCI has closed my ticket with the resolution "Melinda was not a member of the VINCI access security group but is now. Please try again when you have some time."

I have successfully been able to access the Standard Workspace. However, when trying to access the Development Workspace I ran into the following error:

<details>
<summary>Error message</summary>
<br>

![error message](https://github.com/dchan-lab/dchanlab/assets/127564107/a3ca4640-9daa-42ae-addc-8e58f07d1972)

</details>

Should I email VINCI again about this?

**Comment by jessekozler** [comment]
@melinda-xu hmm, I would think that authorization would have come from @chand04 as detailed in the Applying for Remote Access [section](https://github.com/dchan-lab/dchanlab/wiki/Accessing-VA-Data#applying-for-remote-access) of the wiki. Can you confirm whether you received that notification from vansocwebadmin@va.gov?

**Comment by chand04** [comment]
@jessekozler @melinda-xu, I agree that this is strange. Getting remote access as detailed in the wiki doesn't differentiate between workspaces. @jessekozler, let's make sure we understand this with VINCI.

**Comment by melinda-xu** [comment]
@jessekozler, I received emails from the Remote Access Portal from DoNotReply@va.gov confirming that I have been approved for remote access to the VA intranet through both Citrix and Microsoft Azure.

**Comment by jessekozler** [comment]
@chand04 @melinda-xu I just rechecked the [wiki](https://github.com/dchan-lab/dchanlab/wiki/Administrative-Tasks#administering-the-private-server) and I believe it is my responsibility as the server admin to add you as a user to the Development Workspace as the final step of getting access. I am remote today and need the VA machine in the office for this, so I will do it first thing in the morning tomorrow!

**Comment by jessekozler** [comment]
@chand04 I've added @melinda-xu to the Development Workspace and she has confirmed that she is able to log in!

For future Server Admins: this is accomplished by navigating to `Control Panel -> User Accounts -> Give other users access to this computer`. From here, click `Add`, fill in the `Domain` (VHA21) and `User Name` (VHAPAL...) fields, and browse for the correct individual. After adding them, change the `Group` field from "Users" to "Remote Desktop Users" by clicking on the user in question and selecting `Properties`.

Dave, do you think I should add the above bit to the wiki [here](https://github.com/dchan-lab/dchanlab/wiki/Administrative-Tasks#administering-the-private-server)?

**Comment by jessekozler** [comment]
@chand04 I can't say I found it to be terribly self-evident, it definitely took me a few minutes to work out although I'm admittedly not the most tech savvy person, especially when it comes to Windows. You're right that it's a little out-of-step with the level of detail in that section, so I'll defer to you.

**Comment by melinda-xu** [comment]
@chand04 @jessekozler, I still am unable to access Teams. Who should I contact to correct this?

**Comment by chand04** [comment]
@melinda-xu, I would just call the main enterprise help desk, and they should direct you.

**Comment by melinda-xu** [comment]
## Summary

In this issue, we tracked my onboarding progress. These tasks included reading through the wiki, SQL tutorials, VA orientation, and GitHub and SQL onboarding tasks. I have learned a lot about the lab's workflow, SQL and GitHub. 

This task also led to the creation of issue https://github.com/dchan-lab/dchanlab/issues/185 to add me all DART projects, update the IRB for the reminders project, and updating the IRB submission date for "Heterogeneous Treatment Effects and the Diffusion of New Therapies".
