### ISSUE TITLE
Add Melinda to DART Projects

### ISSUE THREAD

**Issue by jtprates** [dchan-lab/dchanlab#185]
In this issue, we will track adding @melinda-xu to our projects in DART. See #141 for an example of how this was done.

**Comment by jtprates** [comment]
@chand04, the DART project for reminders has an outdated IRB expiration date. We'd have to change that before amending the request, but I don't think I can see this project on eProtocol to get the latest IRB. When you have the chance, could you add me to that project or upload the latest eProtocol letter into the reminders repo?

**Comment by chand04** [comment]
@jtprates, hmm, it's odd that we didn't address this in #176. It appears that @jessekozler is on the eProtocol for that project. @jessekozler, can you ensure that all lab members are on the relevant platforms for `reminders`, including eProtocol?

**Comment by jtprates** [comment]
@chand04 , we have a PTR for "Heterogeneous Treatment Effects and the Diffusion of New Therapies", which has an expected IRB submission date of 9/30/2022. We have to change this date before adding Melinda to that folder. Do you think changing it to 9/30/2024 would be acceptable?

**Comment by chand04** [comment]
Sounds good, thanks, @jtprates.

**Comment by jtprates** [comment]
@chand04, as I mentioned in today's check-in, Melinda has been added to all DART projects. I am now closing this issue.

**Comment by jtprates** [comment]
### SUMMARY ###

In this issue, we have added @melinda-xu to all our project folders on DART. 

In the middle of this process, we also updated the IRB for the reminders project on DART, as well as the expected IRB submission date for "Heterogeneous Treatment Effects and the Diffusion of New Therapies" (https://github.com/dchan-lab/dchanlab/issues/185#issuecomment-1638772209).
